# Generated by Django 5.2.3 on 2025-06-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagement', '0002_alter_course_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
